name: CI

on:
  push:
    branches: 
    - staging
    - main

env:
  appname: stunning-umbrella

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: 'version'
      id: version
      shell: bash
      run: |
        branchName="${GITHUB_REF#refs/heads/}"
        imageRepository="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        echo "$branchName"
        echo "$imageRepository"
        echo BRANCH_NAME=$branchName >> $GITHUB_ENV
        echo IMAGE_REPOSITORY=$imageRepository >> $GITHUB_ENV
       
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build and push image'
      run: |
        docker build --tag ${{ env.IMAGE_REPOSITORY}}:${{ github.sha }} --tag ${{ env.IMAGE_REPOSITORY}}:${{ env.BRANCH_NAME }} -f build/Dockerfile .
        docker push --all-tags ${{ env.IMAGE_REPOSITORY}}
      env:
        appname: '${{env.appname}}'
        
    - name: 'Deploy to Azure Web App (main)'
      if: ${{ env.BRANCH_NAME == 'main' }}
      uses: azure/webapps-deploy@v2
      with:
        app-name: '${{env.appname}}'
        slot-name: 'production'
        images: '${{ env.IMAGE_REPOSITORY}}:${{ github.sha }}'
      env:
        appname: '${{env.appname}}'

    - name: 'Azure logout'
      run: |
        az logout
        
